### ISSUE TITLE
[Meta] Missing documentation

### ISSUE THREAD

**Issue by recidive** [recidive/choko#236]
We'll put here a list of things that's missing documentation. Eventually we may create individual issues for them, but for now let's put a list together.

## Content types

- [ ] Content extension and content types
- [ ] Core content types
- [ ] Creating content types (via admin and via JSON)

## Contexts

- [ ] Context conditions and reactions
- [ ] Core contexts (how to override them)
- [ ] Creating contexts (via admin and via JSON)

## Displays

- [ ] Creating displays
- [ ] Displays vs. displays instances
- [ ] Core displays

**Comment by wlsf82** [comment]
I would like to suggest some documentation about navigation creation also.

**Comment by recidive** [comment]
Alright @wlsf82 I saw your issues. I was just going through every Choko extension to put together a list of things that needs to be documented, I've not hit the navigation extension yet but I'm aware of your request. Thanks.
